/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_teamdeadbolts_basler_BaslerJNI */

#ifndef _Included_org_teamdeadbolts_basler_BaslerJNI
#define _Included_org_teamdeadbolts_basler_BaslerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    isLibraryWorking
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_isLibraryWorking(JNIEnv *, jclass);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getCameraModelRaw
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getCameraModelRaw(JNIEnv *, jclass,
                                                          jstring);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getConnectedCameras
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getConnectedCameras(JNIEnv *, jclass);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    createCamera
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_createCamera(JNIEnv *, jclass, jstring);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    startCamera
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_startCamera(JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    stopCamera
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_stopCamera(JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    destroyCamera
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_destroyCamera(JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    setExposure
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_org_teamdeadbolts_basler_BaslerJNI_setExposure(
    JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    setGain
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_org_teamdeadbolts_basler_BaslerJNI_setGain(
    JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    setAutoExposure
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_setAutoExposure(JNIEnv *, jclass, jlong,
                                                        jboolean);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    setFrameRate
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_org_teamdeadbolts_basler_BaslerJNI_setFrameRate(
    JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    setWhiteBalance
 * Signature: (J[D)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_setWhiteBalance(JNIEnv *, jclass, jlong,
                                                        jdoubleArray);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    setAutoWhiteBalance
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_setAutoWhiteBalance(JNIEnv *, jclass,
                                                            jlong, jboolean);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    setPixelFormat
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_setPixelFormat(JNIEnv *, jclass, jlong,
                                                       jint);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getExposure
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getExposure(JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getGain
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getGain(JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getAutoExposure
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getAutoExposure(JNIEnv *, jclass,
                                                        jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getFrameRate(JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getWhiteBalance
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getWhiteBalance(JNIEnv *, jclass,
                                                        jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getAutoWhiteBalance
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getAutoWhiteBalance(JNIEnv *, jclass,
                                                            jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getSupportedPixelFormats
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getSupportedPixelFormats(JNIEnv *,
                                                                 jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    takeFrame
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_takeFrame(JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    awaitNewFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_awaitNewFrame(JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    getPixelFormat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_teamdeadbolts_basler_BaslerJNI_getPixelFormat(JNIEnv *, jclass, jlong);

/*
 * Class:     org_teamdeadbolts_basler_BaslerJNI
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_teamdeadbolts_basler_BaslerJNI_cleanUp(JNIEnv *,
                                                                       jclass);

#ifdef __cplusplus
}
#endif
#endif
