name: Publish Package

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Pylon SDK 7.5
        run: |
          wget -q https://downloads-ctf.baslerweb.com/dg51pdwahxgw/2Yng7CRH1jg02IKHvbUsNR/6adf0ef8b4d37cd33d37f432065893b8/pylon-7.5.0.15658_linux-x86_64_setup.tar.gz
          sudo mkdir -p /opt/pylon /tmp/pylon_install
          sudo tar -xzf pylon-7.5.0.15658_linux-x86_64_setup.tar.gz -C /tmp/pylon_install
          sudo tar -xf /tmp/pylon_install/pylon-7.5.0.15658_linux-x86_64.tar.gz -C /opt/pylon --strip-components=1
          sudo rm -rf /tmp/pylon_install pylon-7.5.0.15658_linux-x86_64_setup.tar.gz
        shell: bash

      - name: Build and Publish
        run: |
          export LD_LIBRARY_PATH=/opt/pylon/lib64:$LD_LIBRARY_PATH
          export PYLON_ROOT=/opt/pylon
          
          nix-shell --run "./gradlew build publish --no-configuration-cache"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          GITHUB_ACTOR: ${{ github.actor }}